<?php

return [
    'directories' => [
        'Plugin' => '/plugins',
        'Mod' => '/mods',
        'Datapack' => '/world/datapacks',
    ],
    'catalog' => [
        ['id' => 'luckperms', 'name' => 'LuckPerms', 'author' => 'lucko', 'category' => 'Plugin', 'description' => 'A powerful, flexible permissions plugin with per-group and per-user control.', 'version' => '5.4.130', 'downloads' => '48.2M', 'rating' => 4.9, 'file' => 'LuckPerms-Bukkit.jar', 'url' => 'https://download.luckperms.net/1554/bukkit/loader/LuckPerms-Bukkit-5.4.130.jar'],
        ['id' => 'essentialsx', 'name' => 'EssentialsX', 'author' => 'EssentialsX Team', 'category' => 'Plugin', 'description' => 'The essential toolkit: homes, warps, kits, economy and hundreds of commands.', 'version' => '2.20.1', 'downloads' => '61.7M', 'rating' => 4.8, 'file' => 'EssentialsX.jar', 'url' => 'https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsX-2.20.1.jar'],
        ['id' => 'worldedit', 'name' => 'WorldEdit', 'author' => 'EngineHub', 'category' => 'Plugin', 'description' => 'In-game map editor. Build fast, remove terrain and fix griefing in seconds.', 'version' => '7.3.6', 'downloads' => '39.0M', 'rating' => 4.9, 'file' => 'worldedit-bukkit.jar', 'url' => 'https://dev.bukkit.org/projects/worldedit/files/latest'],
        ['id' => 'vault', 'name' => 'Vault', 'author' => 'MilkBowl', 'category' => 'Plugin', 'description' => 'Abstraction layer for economy, permissions and chat used by most plugins.', 'version' => '1.7.3', 'downloads' => '55.4M', 'rating' => 4.7, 'file' => 'Vault.jar', 'url' => 'https://github.com/MilkBowl/Vault/releases/download/1.7.3/Vault.jar'],
        ['id' => 'dynmap', 'name' => 'Dynmap', 'author' => 'webbukkit', 'category' => 'Plugin', 'description' => 'Google-Maps-style live web map of your world, updated in real time.', 'version' => '3.7', 'downloads' => '21.9M', 'rating' => 4.6, 'file' => 'Dynmap.jar', 'url' => 'https://dev.bukkit.org/projects/dynmap/files/latest'],
        ['id' => 'viaversion', 'name' => 'ViaVersion', 'author' => 'ViaVersion', 'category' => 'Plugin', 'description' => 'Let newer clients join older servers. Keep one version, support many.', 'version' => '5.1.1', 'downloads' => '44.3M', 'rating' => 4.8, 'file' => 'ViaVersion.jar', 'url' => 'https://github.com/ViaVersion/ViaVersion/releases/download/5.1.1/ViaVersion-5.1.1.jar'],
        ['id' => 'geyser', 'name' => 'Geyser', 'author' => 'GeyserMC', 'category' => 'Plugin', 'description' => 'Bridge that lets Bedrock Edition players join your Java server.', 'version' => '2.4.2', 'downloads' => '18.6M', 'rating' => 4.7, 'file' => 'Geyser-Spigot.jar', 'url' => 'https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot'],
        ['id' => 'coreprotect', 'name' => 'CoreProtect', 'author' => 'Intelli', 'category' => 'Plugin', 'description' => 'Fast block logging and rollback tool to undo grief and inspect changes.', 'version' => '22.4', 'downloads' => '29.1M', 'rating' => 4.9, 'file' => 'CoreProtect.jar', 'url' => 'https://github.com/PlayPro/CoreProtect/releases/download/v22.4/CoreProtect-22.4.jar'],
        ['id' => 'spark', 'name' => 'spark', 'author' => 'lucko', 'category' => 'Plugin', 'description' => 'Performance profiler to find lag spikes, tick stalls and memory issues.', 'version' => '1.10.53', 'downloads' => '15.4M', 'rating' => 4.8, 'file' => 'spark.jar', 'url' => 'https://ci.lucko.me/job/spark/lastSuccessfulBuild/artifact/spark-bukkit/build/libs/spark-1.10.53-bukkit.jar'],
        ['id' => 'chunky', 'name' => 'Chunky', 'author' => 'pop4959', 'category' => 'Plugin', 'description' => 'Pre-generate your world in the background to cut lag when players explore.', 'version' => '1.4.28', 'downloads' => '12.1M', 'rating' => 4.8, 'file' => 'Chunky.jar', 'url' => 'https://cdn.modrinth.com/data/fALzjamp/versions/Chunky-Bukkit-1.4.28.jar'],
        ['id' => 'bluemap', 'name' => 'BlueMap', 'author' => 'Blue (TBlueF)', 'category' => 'Plugin', 'description' => 'Generates a beautiful 3D web map of your world you can explore in a browser.', 'version' => '5.4', 'downloads' => '6.8M', 'rating' => 4.7, 'file' => 'BlueMap.jar', 'url' => 'https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v5.4/bluemap-5.4-spigot.jar'],
        ['id' => 'fabric-api', 'name' => 'Fabric API', 'author' => 'FabricMC', 'category' => 'Mod', 'description' => 'Core hooks and interoperability layer required by most Fabric mods.', 'version' => '0.100.4', 'downloads' => '112M', 'rating' => 4.9, 'file' => 'fabric-api.jar', 'url' => 'https://cdn.modrinth.com/data/P7dR8mSH/versions/fabric-api-0.100.4.jar'],
        ['id' => 'lithium', 'name' => 'Lithium', 'author' => 'CaffeineMC', 'category' => 'Mod', 'description' => 'General-purpose optimization mod that boosts server tick performance.', 'version' => '0.13.0', 'downloads' => '34.8M', 'rating' => 4.9, 'file' => 'lithium.jar', 'url' => 'https://cdn.modrinth.com/data/gvQqBUqZ/versions/lithium-0.13.0.jar'],
        ['id' => 'simple-voice-chat', 'name' => 'Simple Voice Chat', 'author' => 'henkelmax', 'category' => 'Mod', 'description' => 'Adds proximity voice chat to your server with a slick, configurable UI.', 'version' => '2.5.26', 'downloads' => '28.9M', 'rating' => 4.9, 'file' => 'voicechat.jar', 'url' => 'https://cdn.modrinth.com/data/9eGKb6K1/versions/voicechat-fabric-2.5.26.jar'],
        ['id' => 'terralith', 'name' => 'Terralith', 'author' => 'Stardust Labs', 'category' => 'Datapack', 'description' => 'Overhauls world generation with 100+ new biomes using only vanilla blocks.', 'version' => '2.5.4', 'downloads' => '9.2M', 'rating' => 4.8, 'file' => 'Terralith.zip', 'url' => 'https://cdn.modrinth.com/data/8oi3bsk5/versions/terralith-2.5.4.zip'],
        ['id' => 'vanilla-tweaks', 'name' => 'Vanilla Tweaks', 'author' => 'VanillaTweaks', 'category' => 'Datapack', 'description' => 'A pick-and-choose bundle of quality-of-life datapacks for survival worlds.', 'version' => '1.20', 'downloads' => '7.5M', 'rating' => 4.7, 'file' => 'VanillaTweaks.zip', 'url' => 'https://vanillatweaks.net/download/VanillaTweaks.zip'],
    ],
];
